"""empty message

Revision ID: 51b2948a962a
Revises: 58977875af64
Create Date: 2013-10-30 00:40:55.250000

"""

# revision identifiers, used by Alembic.
revision = '51b2948a962a'
down_revision = '58977875af64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=67), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
