"""empty message

Revision ID: 58977875af64
Revises: None
Create Date: 2013-10-24 00:22:33.540000

"""

# revision identifiers, used by Alembic.
revision = '58977875af64'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('email', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'email')
    ### end Alembic commands ###
